---
sidebar: sidebar
permalink: workflows/wf_list_backups.html
keywords:
summary: You can list the backups that have been created for a specific application.
---

= List the backups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can list the backups that have been created for a specific application.

=== Before you begin

You must have the ID of the app you want to list the backups for. If needed you can use the workflow link:wf_list_man_apps.html[List the apps] to locate the application.

=== 1. List the backups

Perform the following REST API call.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups
|===

===== Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl examples for this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|app id
|Path
|Yes
|Identifies the managed application owning the listed backups.
|===

===== Curl example: Return all backups for the app
[source,curl]
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'

===== JSON output example
[source,json]
{
    "items": [
        {
            "type": "application/astra-appBackup",
            "version": "1.1",
            "id": "8edeb4a4-fd8b-4222-a559-1013145b28fc",
            "name": "backup-david-oct28-1",
            "bucketID": "a443e58f-59bd-4d45-835a-1bc7813f659a",
            "snapshotID": "dfe237cb-57b7-4576-af4d-00ba3a8f2828",
            "state": "completed",
            "stateUnready": [],
            "hookState": "success",
            "totalBytes": 205219132,
            "bytesDone": 205219132,
            "percentDone": 100,
            "metadata": {
                "labels": [
                    {
                        "name": "astra.netapp.io/labels/read-only/triggerType",
                        "value": "backup"
                    }
                ],
                "creationTimestamp": "2022-10-28T21:58:37Z",
                "modificationTimestamp": "2022-10-28T21:58:55Z",
                "createdBy": "a530e865-23e8-4e2e-8020-e92c419a3867"
            }
        }
    ],
    "metadata": {}
}
